[package]
name = "healthmon"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
clap = { version = "4", features = ["derive"] }
futures-util = "0.3"
bollard = { version = "0.16" }
common = { path = "../common" }
